- job_name: 'kubernetes-service-endpoints'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: https
    kubernetes_sd_configs:
    - api_server: https://api_server_url:8443
      role: endpoints
      bearer_token: <paste_the_token_here>
      tls_config:
        insecure_skip_verify: true

    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_demoapp_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_demoapp_scheme]
        action: replace
        target_label: __scheme__
        regex: (http?)
      - source_labels: [__meta_kubernetes_service_annotation_demoapp_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__meta_kubernetes_pod_host_ip, __meta_kubernetes_service_annotation_demoapp_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod